name: Build, Publish & Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ secrets.DOCKER_USER }}/dm_fe:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile        # hoặc Dockerfile.react / Dockerfile.next
          push: true
          tags: ${{ secrets.DOCKER_USER }}/dm_fe:latest

  deploy:
    name: Deploy to Server via SSH
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Pull new image, Restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Logging in to Docker registry..."
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login  -u ${{ secrets.DOCKER_USER }} --password-stdin
            echo "Pulling Docker image from Docker registry..."
           
            docker pull ${{ secrets.DOCKER_USER }}/dm_fe:latest

            echo "Stopping old container (if exists)..."
            docker stop dm_fe || true
            docker rm dm_fe || true

            echo "Starting new container..."
            docker run -d \
              --name dm_fe \
              -p 80:80 \
              ${{ secrets.DOCKER_USER }}/dm_fe:latest
